# Generated by Django 2.1.3 on 2018-11-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_model',
            field=models.BooleanField(default=False),
        ),
    ]
