# Generated by Django 2.1.3 on 2018-11-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_model',
            new_name='is_admin',
        ),
    ]
