# Generated by Django 2.1.3 on 2018-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181115_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='exit', upload_to='users/pictures'),
            preserve_default=False,
        ),
    ]
